FROM node:22-alpine3.18 as build

WORKDIR /app

COPY package*.json ./


COPY . .

RUN npm install
RUN npm install --save-dev nodemon jest
# RUN npm install express near-api-js dotenv cors helmet
RUN npm install express --save

# Create necessary directories
RUN mkdir -p .logs uploads/images

# Create a non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown -R appuser:appgroup /app

USER appuser

# EXPOSE 3000

CMD ["npm", "start"]